(ns skazka.api-keys)

(def api-keys
  [[:produce 0 "Produce" false]
   [:fetch 1 "Fetch" false]
   [:list-offsets 2 "ListOffsets" false]
   [:metadata 3 "Metadata" false]
   [:leader-and-isr 4 "LeaderAndIsr" true]
   [:stop-replica 5 "StopReplica" true]
   [:update-metadata 6 "UpdateMetadata" true]
   [:controlled-shutdown 7 "ControlledShutdown" true]
   [:offset-commit 8 "OffsetCommit" false]
   [:offset-fetch 9 "OffsetFetch" false]
   [:find-coordinator 10 "FindCoordinator" false]
   [:join-group 11 "JoinGroup" false]
   [:heartbeat 12 "Heartbeat" false]
   [:leave-group 13 "LeaveGroup" false]
   [:sync-group 14 "SyncGroup" false]
   [:describe-groups 15 "DescribeGroups" false]
   [:list-groups 16 "ListGroups" false]
   [:sasl-handshake 17 "SaslHandshake" false]
   [:api-versions 18 "ApiVersions" false]
   [:create-topics 19 "CreateTopics" false]
   [:delete-topics 20 "DeleteTopics" false]
   [:delete-records 21 "DeleteRecords" false]
   [:init-producer-id 22 "InitProducerId" false]
   [:offset-for-leader-epoch 23 "OffsetForLeaderEpoch" false]
   [:add-partitions-to-txn 24 "AddPartitionsToTxn" false]
   [:add-offsets-to-txn 25 "AddOffsetsToTxn" false]
   [:end-txn 26 "EndTxn" false]
   [:write-txn-markers 27 "WriteTxnMarkers" true]
   [:txn-offset-commit 28 "TxnOffsetCommit" false]
   [:describe-acls 29 "DescribeAcls" false]
   [:create-acls 30 "CreateAcls" false]
   [:delete-acls 31 "DeleteAcls" false]
   [:describe-configs 32 "DescribeConfigs" false]
   [:alter-configs 33 "AlterConfigs" false]
   [:alter-replica-log-dirs 34 "AlterReplicaLogDirs" false]
   [:describe-log-dirs 35 "DescribeLogDirs" false]
   [:sasl-authenticate 36 "SaslAuthenticate" false]
   [:create-partitions 37 "CreatePartitions" false]
   [:create-delegation-token 38 "CreateDelegationToken" false]
   [:renew-delegation-token 39 "RenewDelegationToken" false]
   [:expire-delegation-token 40 "ExpireDelegationToken" false]
   [:describe-delegation-token 41 "DescribeDelegationToken" false]
   [:delete-groups 42 "DeleteGroups" false]
   [:elect-leaders 43 "ElectLeaders" false]
   [:incremental-alter-configs 44 "IncrementalAlterConfigs" false]
   [:alter-partition-reassignments 45 "AlterPartitionReassignments" false]
   [:list-partition-reassignments 46 "ListPartitionReassignments" false]
   [:offset-delete 47 "OffsetDelete" false]])

(defn ->keyword [api-key-short]
  (nth (nth api-keys api-key-short) 0))
